feat: Gmail / IMAP importer (commandline only)
ddavness/power-mailinabox pull request #57
Opened 2022-06-14 03:14 UTC by casesolved-co-uk

Uses offlineimap to allow you to:

- Import specific remote Gmail/IMAP folders to your MIAB mailbox (yes it preserves your Gmail labels)
- Export your MIAB mailbox folders to Gmail/IMAP (yes it also preserves your Gmail labels)

So yes you can use it to migrate from one Gmail account to another via MIAB!
Currently draft because the export hasn't been tested yet, but import works.

2022-06-17 03:49 UTC, casesolved-co-uk commented
Export currently at 36.2% on my mailbox..

2022-06-24 18:04 UTC, Programming4People commented
The export may be stuck due to throttling by google... 

explained here: https://support.google.com/a/answer/1071518

just wasted a day shuttling between google support for admin, migration and email team (three seperate teams) and they say that the problem is due to throttling and maxing out day downloads....

2022-06-24 18:29 UTC, ddavness commented
I wonder how useful would it be to support something like https://takeout.google.com - basically you can use it to ask Google to crunch your entire mailbox into a .zip file. Though it will take a while until you can download that file (depends on how full your mailbox is), but after that there will be no throttling since we'll be just using that file.

2022-06-24 18:40 UTC, Programming4People commented
Absolutely interesting..  I have been shuttling now for 3 days attempting to get a format of what the data looks like..  Google has great tools for IMPORTING.. but they are like hotel California.. you can check in ... but you will jump through hoops before you can leave....

I shall have data for one domain... so I can see...  

Another issue is you can only do one export every 30 days.. so you have to have mailserver all set up.. It is easy to download a list of google apps users...  but aliases?  groups? no way.. you have to do by hand.. insane.

Another issue is that Legacy had a 15G max size storage...    I have spent the entire day dealing now with Migration group.. and they are seeing if I try to do an export of a domain that has a TOTAL  greater then 15 G  will it work.  We have one domain that has several accounts  that are close to the limit...

(this is the question that google's migration has been working on solving)
<QUOTE>
so.. just to ensure I am clear..  if we have 4 users.. close to 14 gigs each in space.. and admin does export... (so total is close to 56G) are we able to download entire space...
as admin that is also limited to 15G?
<END QUOTE>

2022-06-24 18:59 UTC, Programming4People commented
Again just got confirmation from same person ( Adita) that depending on mail messages 


"The emails will be in .pst or .mbox" 7:53 PM
                                                                             ME-> ok. thanks.. and what decides on the difference?

Google Workspace Support, Aditya 7:54 PM
It depends on the size of the file

Google Workspace Support, Aditya7:57 PM
Apart from this, is there anything else I can help you with?
7:57 PM
                                                                 ME -> and just to confirm.. you are with what team?
Google Workspace Support, Aditya7:57 PM
I am from the Admin team.

2022-06-24 19:27 UTC, casesolved-co-uk commented
I think you've missed the point of this addon.
It uses IMAP to download (import) each gmail message in maildir format to a MIAB mailbox. If it fails for whatever reason it will resume.
It also downloads the message labels.

Then if you want you can upload/export to another gmail mailbox.

My export wasn't stuck, just reporting that export was working.

2022-06-24 22:50 UTC, casesolved-co-uk commented
The import was already complete. Export also completed.
IMAP should also resume once your daily limit is reset.

2022-06-24 23:17 UTC, Programming4People commented
so after starting export.. next surprise:  from 72 hrs to 9 days....

email from google:
------

Data export for DOMAIN successfully started

Hello,

A super administrator of your Google Account has started exporting data for DOMAIN. Data export typically takes 72 hours  but can take up to 9 days, depending on the size of your data export. You'll get a confirmation email when the export is complete. You can see the current status of the export in the [Data Export tool](https://admin.google.com/ac/customertakeout).

For more information about the Data export tool, see [Export your organization’s data](https://support.google.com/a/answer/100458?utm_source=7629471&utm_medium=email).

Sincerely,
The Google Workspace Team

------

2022-10-09 19:46 UTC, Craxa approved these changes
yes

2022-12-07 16:13 UTC, casesolved-co-uk commented
@ddavness I've rebased onto your latest changes. Are there any issues with this?

2022-12-07 17:25 UTC, ddavness commented
Taking a look! :)

2022-12-07 19:59 UTC, ddavness requested changes
Some thoughts:
- We probably should support having interactive remote user/password input;
- When using the Gmail method, it's probably safe to assume that `remotehost` is `imap.gmail.com` and that `remoteport` is `993`;
- Also see the individual reviews I left :)

2022-12-07 19:59 UTC, ddavness commented on management/imapimport.py
> +		if cmd not in ('import', 'export') or type not in ('Gmail', 'IMAP') or not user:
It's important to expect that users will not always use properly captialized terms. For example, `gmail` instead of `Gmail` and `imap` instead of `IMAP`. We should account and correct for these.

```suggestion
		if cmd.lower() not in ('import', 'export') or type.lower() not in ('gmail', 'imap') or not user:
```

Furthermore consider creating more specific error messages for each of these failure conditions (`cmd`, `type` and `user`)

2022-12-07 20:22 UTC, casesolved-co-uk commented on management/imapimport.py
> +		raise
... along with the usage telling you what the parameters are

2022-12-07 20:23 UTC, casesolved-co-uk commented on management/imapimport.py
> +		if cmd not in ('import', 'export') or type not in ('Gmail', 'IMAP') or not user:
I don't think this will work because the parameters are used to render the config file: render = text.format(**context)

Realistically, I don't really expect people to use the commandline version. It really needs a UI where all this can be drop-downs and validated fields

2022-12-08 01:37 UTC, ddavness commented on management/imapimport.py
> +		if cmd not in ('import', 'export') or type not in ('Gmail', 'IMAP') or not user:
> Realistically, I don't really expect people to use the commandline version.

Until a TUI or GUI is implemented people will use the command line because that's the only way they can do so.

So I'd rather have a good CLI right off the bat regardless if we're going to also make this available within roundcube or the admin panel.

2022-12-08 05:26 UTC, casesolved-co-uk commented on management/imapimport.py
> +		if cmd not in ('import', 'export') or type not in ('Gmail', 'IMAP') or not user:
I've made the errors a bit more specific.

Adding too much intelligence like automatically completing the gmail imap server is going to make it more difficult to implement a UI because the parameters will move around.

I don't have time to implement any more changes, sorry.

2023-04-27 01:10 UTC, ddavness approved these changes
While the PR isn't ready IMO as-is for release, I'll accept it for merging on a separate development branch - so that I can make some changes to make it more user-friendly and carry on with your work.

Massive thanks for this btw :smile:

2023-04-27 01:10 UTC, merged